# appveyor file:
# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/environment-variables

version: "{build}"

# blacklist
#except:
#  - gh-pages

build: false

environment:
    matrix:
      - PYTHON: "C:\\Python36-x64"
        PY_PYTHON: 3.6
        PY_PYTHON3: 3.6
        PYTHON_VERSION: "3.6.x"
        PYTHON_ARCH: "64"

      - PYTHON: "C:\\Python37-x64"
        PY_PYTHON: 3.7
        PY_PYTHON3: 3.7
        PYTHON_VERSION: "3.7.x"
        PYTHON_ARCH: "64"

platform:
    - AnyCPU

init:
    # http://www.appveyor.com/docs/how-to/rdp-to-build-worker
    #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    - echo %PYTHON%
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - set
    # Check that we have the expected version and architecture for Python
    - "python --version"
    - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
    - "py -V"
    - "py -c \"import sys; print(sys.version)\""
    - "py -3 -V"
    - "py -3 -c \"import sys; print(sys.version)\""

# clone directory
clone_folder: c:/pyhardlinkbackup_clone

# set clone depth
clone_depth: 5 # clone entire repository history if not defined

install:
    - cd c:/pyhardlinkbackup_clone
    - "py -3 -c \"from dev.patch_cmd import patch;patch('boot_pyhardlinkbackup.cmd', debug=False)\""
    - boot_pyhardlinkbackup.cmd
    - cd "%ProgramFiles%/PyHardLinkBackup/Scripts"
    - set PATH=%ProgramFiles%/PyHardLinkBackup/Scripts;%PATH%
    - pip uninstall -y PyHardLinkBackup
    - pip install -e git+https://github.com/jedie/PyHardLinkBackup.git#egg=pyhardlinkbackup
    - pip install appveyor-artifacts
    - cd "%ProgramFiles%/PyHardLinkBackup/src/pyhardlinkbackup"
    - git fetch
    - git checkout -qf %APPVEYOR_REPO_COMMIT%
    - manage.exe migrate
    - phlb.exe helper "%ProgramFiles%/PyHardLinkBackup"

test_script:
    - cd "%ProgramFiles%/PyHardLinkBackup"
    - call phlb_run_tests.cmd no_report
    - cd "%ProgramFiles%/PyHardLinkBackup/src/pyhardlinkbackup"

artifacts:
    - path: .coverage

on_finish:
    - cd "%ProgramFiles%/PyHardLinkBackup/src/pyhardlinkbackup"
    - coverage combine
    - coverage report

#    - set COVERALLS_REPO_TOKEN=3uErcCZvScP0LKMj9qcgab67qRsu8XnSQ
#    - coveralls

    # http://www.appveyor.com/docs/how-to/rdp-to-build-worker
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
