name: test

on:
  schedule:
    - cron: '0 8 * * *'
  push:

jobs:
  test:
    name: Python ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.7, 3.6, pypy3]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v1
      with:
        python-version: '${{ matrix.python-version }}'

    - name: 'Install package'
      run: |
        pip3 install poetry
        make install
        pip3 install tox-gh-actions

    - name: 'List installed packages'
      run: |
        poetry run pip freeze

    - name: 'List all tox test environments'
      run: |
        make tox-listenvs

    - name: 'Run pytest with tox'
      run: |
        make tox

    - name: 'Upload coverage report'
      continue-on-error: true
      run: bash <(curl -s https://codecov.io/bash)

    - name: 'Run linters'
      if: matrix.python-version == '3.8'
      run: |
        make lint
